### ISSUE TITLE
Reduce delay to 0 if using cache

### ISSUE THREAD

**Issue by philmaweb** [biothings/mygene.py#10]
I'm trying to translate a large list of Mouse ensembl geneIDs to refseq genes. I enabled a cache - but it takes exactly the same amount of time to rerun the same query - shouldn't the delay be set off or zero if using a cache? One can simply check for the existence of the genes in the DB or manage an index / dictionary to skip lookups.

Right now I do my own caching, as re-running the same query takes >30 seconds with or without the builtin cache (so no advantage in speed, only saving bandwidth).

Example:
```
import mygene
mg = mygene.MyGeneInfo()
mg.set_caching("genes.db")
mouse_symbol_df2 = mg.getgenes(expr_df['ensembl'].values, as_dataframe=True, 
                              fields=['ensembl.gene', 'symbol', 'entrezgene', 'name'], 
                              species='mouse')
```

**Comment by newgene** [comment]
@philmaweb good point! Thanks for catching this, we will make a quick fix on this.

**Comment by newgene** [comment]
And I should mention that, before we fix it, you can always set the delay to 0 in your own code:

```
In [1]: import mygene
In [2]: mg = mygene.MyGeneInfo()
In [3]: mg
Out[3]: <mygene.MyGeneInfo at 0x7ff9aead09e8>
In [4]: mg.delay
Out[4]: 1
In [5]: mg.delay = 0
```

@philmaweb

**Comment by newgene** [comment]
fixed in https://github.com/biothings/biothings_client.py/commit/9c36b66796f4d55a963d96fd15045a6872ffebda
