### ISSUE TITLE
setting entrezonly=True for querymany does not work

### ISSUE THREAD

**Issue by dhimmel** [biothings/mygene.py#11]
The [docs](http://docs.mygene.info/en/latest/doc/query_service.html#entrezonly) for `entrezonly`

> Optional, when passed as “true” or “1”, the query returns only the hits with valid Entrez gene ids. Default: false.

But the following command:

```python
import mygene
mg_info = mygene.MyGeneInfo()
results = mg_info.querymany(
    ['FAM86B3P'],
    scopes=["symbol", "alias"],
    species='9606',
    fields=["_score", "symbol", "entrezgene", "ensembl.gene", "name"],
    entrezonly=True,
)
results
```

Returns results without `entrezgene` and where `_id` is not an entrez geneid:

```python
querying 1-1...done.
Finished.
1 input query terms found dup hits:
	[('FAM86B3P', 3)]
Pass "returnall=True" to return complete lists of duplicate or missing query terms.
[{'query': 'FAM86B3P',
  '_id': 'ENSG00000173295',
  '_score': 36.394867,
  'ensembl': {'gene': 'ENSG00000173295'},
  'name': 'family with sequence similarity 86 member B3, pseudogene',
  'symbol': 'FAM86B3P'},
 {'query': 'FAM86B3P',
  '_id': '286042',
  '_score': 36.386105,
  'entrezgene': '286042',
  'name': 'family with sequence similarity 86, member A pseudogene',
  'symbol': 'FAM86B3P'},
 {'query': 'FAM86B3P',
  '_id': 'ENSG00000285119',
  '_score': 36.384216,
  'ensembl': {'gene': 'ENSG00000285119'},
  'name': 'family with sequence similarity 86 member B3, pseudogene',
  'symbol': 'FAM86B3P'}]
```

**Comment by dhimmel** [comment]
Setting `ensemblonly=True` returns the same as above.

Is there a way to access the underlying API calls `mygene` is making? This would help debug

**Comment by newgene** [comment]
@dhimmel both `entrezonly=true` and `ensemblonly=true` parameters are not supported in the POST queries, as documented here: 

http://docs.mygene.info/en/latest/doc/query_service.html#batch-queries-via-post

They are available for the GET query only right now, but we will have a look to see if we can add this feature to the POST query as well.

**Comment by dhimmel** [comment]
> we will have a look to see if we can add this feature to the POST query as well.

ah that would be helpful. Thanks!

**Comment by namespacestd0** [comment]
Implemented in https://github.com/biothings/mygene.info/commit/58abe4512d604dc1bcc02fd4eb26b358e3f07245
Not deployed on production server yet.

**Comment by dhimmel** [comment]
Thanks @namespacestd0!

**Comment by namespacestd0** [comment]
Deployed a while ago.  The code mentioned above now return entrez only result:
```[{'query': 'FAM86B3P', '_id': '286042', '_score': 38.20171, 'entrezgene': '286042', 'name': 'family with sequence similarity 86, member A pseudogene', 'symbol': 'FAM86B3P'}]```
