### ISSUE TITLE
Query parameters no longer working

### ISSUE THREAD

**Issue by TDMedina** [biothings/mygene.py#17]
Hello,
I'm currently using mygene 3.1.0 with python 3.8.5. Until recently, this was fine, but today the `query` method seems to be acting up. When I pass parameters like `fields` or `species` as shown:

```python
 my_gene_instance.query(q="DUSP22", species="human")
```
I get the following error:
`HTTPError: 400 Client Error: Expect type list. for url: http://mygene.info/v3/query/`

Is this a bug, or should I simply update my package? 

Update: I updated to 3.2.1, and I'm no longer experiencing this issue.

**Comment by newgene** [comment]
@TDMedina this is indeed an issue came recently due to the mismatch between the Python Client and the recently updated MyGene.info API version.

More info here: https://github.com/biothings/mygene.py/issues/16 and https://github.com/biothings/biothings_client.py/issues/17
