### ISSUE TITLE
pandas error 

### ISSUE THREAD

**Issue by marouenbg** [biothings/mygene.py#19]
Hello :wave:

I was trying to export results as pandas dataframe
```
import mygene
mg = mygene.MyGeneInfo()
geneform=['RGS4']
geneSyms = mg.querymany(geneform , scopes=["ensemblgene", "symbol"], fields='ensembl.gene', 
species='human',as_dataframe=True)
```

However, I had the following error 
`Error: pandas module must be installed for as_dataframe option.`

I do have pandas installed. I am using Python 3.6.9, my gene 3.2.2 and pandas  0.25.2 on Ubuntu 18.04

Thank you

**Comment by marouenbg** [comment]
switching to python3.8 solved the problem!

**Comment by namespacestd0** [comment]
Thank you for reporting. We're looking at this issue to ensure cross version compatibilities.

**Comment by newgene** [comment]
@marcodarko, just want to mention that the error you had before seems related to your pandas version. Your above code worked just fine for me with: Python 3.6.9, my gene 3.2.2 and pandas *1.0.1* on Ubuntu 18.04.

**Comment by newgene** [comment]
Updated the error msg to cover the case with an old pandas module: https://github.com/biothings/biothings_client.py/commit/28a02aed2661e04ef140b86fbe35e235aa3b1a44

**Comment by marouenbg** [comment]
@newgene  makes sense, thank you !
