### ISSUE TITLE
Querymany returns a list larger than the original

### ISSUE THREAD

**Issue by LPioL** [biothings/mygene.py#9]
Hi,

I use mygene to translate from uniprot to HGNC:

    out_query =  mg.querymany(genes, scopes = 'uniprot', fields = 'symbol,hgnc', species='human')

outquery has a length larger than genes. We have duplicates in the query with different returned gene symbol.

![image](https://user-images.githubusercontent.com/21370238/68313676-441c3000-00b5-11ea-92aa-056145c279c1.png)

For a specific protein, we have two outputs:

      mg.query('P24462', scopes = 'uniprot', fields = 'symbol', species='human')

Out[45]: 
{'max_score': 24.986576,
 'took': 8,
 'total': 2,
 'hits': [{'_id': '1551', '_score': 24.986576, 'symbol': 'CYP3A7'},
  {'_id': '100861540', '_score': 3.374457, 'symbol': 'CYP3A7-CYP3A51P'}]}

Any idea how to have the same length for the output of manyquery ?

Regards.

**Comment by kevinxin90** [comment]
Hi,
Please specify the JSON structure of your desired output and we can see if there are anything we can do to help.

**Comment by LPioL** [comment]
Well for mg.query, it is a good structure as I can choose between the two outputs. For mg.querymany that I need, it is not as for the same query I have two outputs leading to a dataframe with more entries than the input list which is not really appropriate if I want to keep the order of the input list.

**Comment by kevinxin90** [comment]
I don't think we will change the output structure of mygene querymany function, since this is a very use-specific issue.
And there are some very easy ways you can apply on your end to circumvent it, for example, you could use the python 'groupby' function from the itertools to group the results based on the 'query' field. If you are using pandas dataframe, there are also corresponding groupby features which you could apply.
Thanks!

**Comment by LPioL** [comment]
Ok, I thought this double output was not normal but thanks!

**Comment by kevinxin90** [comment]
Adding to that, if you check the uniprot website: https://www.uniprot.org/uniprot/P24462#section_x-ref_genome

This uniprot id"P24462" does correspond to two gene ids: 100861540 and 1551.
